import { useEffect, useMemo, useState, type ReactNode } from 'react';
import type { Action, DecisionTrace, IncidentStatus, Relationship, Replay, Severity } from '../models';
import { actionLabel, confidence, currentIncidentId, decisionsThrough, filterDecisions, incidentsAtPoint, isReplay, sourceLabel, type IncidentAtPoint } from './replay-view';

type Filter = 'ALL' | 'REVIEW' | Relationship | Severity | IncidentStatus;
const relationships: Relationship[] = ['NEW', 'UPDATE', 'CORROBORATION', 'CONFLICT', 'DUPLICATE', 'RESOLUTION'];

function Badge({ value, kind = 'neutral' }: { value: string; kind?: string }) { return <span className={`badge ${kind} ${value.toLowerCase().replaceAll('_', '-')}`}>{value.replaceAll('_', ' ')}</span>; }
function Confidence({ value }: { value: number }) { return <span className="confidence"><i><b style={{ width: `${value * 100}%` }} /></i>{confidence(value)}</span>; }
function actionsText(actions: Action[]): string { return actions.length ? actions.map(actionLabel).join(', ') : 'No new action'; }
function Empty({ message }: { message: string }) { return <main className="empty"><span>◈</span><h1>Campus Crisis Agent</h1><p>{message}</p><code>npm run predict</code><small>Then refresh the dashboard.</small></main>; }

export default function App() {
  const [replay, setReplay] = useState<Replay | null>(null); const [error, setError] = useState<string | null>(null); const [index, setIndex] = useState(0); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(900); const [selected, setSelected] = useState<string | null>(null); const [filters, setFilters] = useState<Filter[]>(['ALL']);
  useEffect(() => { let mounted = true; fetch('/replay.json').then(async (response) => { if (!response.ok) throw new Error('Replay data is unavailable.'); return response.json() as Promise<unknown>; }).then((data) => { if (!isReplay(data)) throw new Error('Replay data is malformed.'); if (mounted) setReplay(data); }).catch((reason: unknown) => { if (mounted) setError(reason instanceof Error ? reason.message : 'Replay data could not be loaded.'); }); return () => { mounted = false; }; }, []);
  useEffect(() => { if (!playing || !replay) return undefined; const id = window.setInterval(() => setIndex((value) => value >= replay.decisions.length - 1 ? (setPlaying(false), value) : value + 1), speed); return () => window.clearInterval(id); }, [playing, replay, speed]);
  const visible = useMemo(() => replay ? decisionsThrough(replay, index) : [], [replay, index]); const incidents = useMemo(() => replay ? incidentsAtPoint(replay, index) : [], [replay, index]); const current = visible.at(-1); const detail = incidents.find((item) => item.incident.incidentId === (selected ?? current?.prediction.incident_id)) ?? incidents[0];
  const filtered = useMemo(() => filterDecisions(visible, filters), [visible, filters]);
  if (error) return <Empty message={error} />; if (!replay) return <Empty message="Loading replay data…" />; if (!current) return <Empty message="No replay data available. Run prediction generation first." />;
  const active = incidents.filter((item) => ['ACTIVE', 'ESCALATED'].includes(item.last.prediction.incident_status)).length; const resolved = incidents.filter((item) => item.last.prediction.incident_status === 'RESOLVED').length; const conflicts = visible.filter((item) => item.prediction.relationship === 'CONFLICT').length; const reviews = visible.filter((item) => item.prediction.human_review).length;
  const move = (next: number) => { const target = Math.max(0, Math.min(replay.decisions.length - 1, next)); setPlaying(false); setIndex(target); setSelected(currentIncidentId(replay, target)); }; const toggle = (filter: Filter) => setFilters((values) => { if (filter === 'ALL') return ['ALL']; const withoutAll = values.filter((value) => value !== 'ALL'); return withoutAll.includes(filter) ? withoutAll.filter((value) => value !== filter) : [...withoutAll, filter]; });
  return <main className="dashboard"><header><div><p className="eyebrow">AGENTIC INCIDENT OPERATIONS</p><h1>Campus Crisis Agent</h1><p className="subtitle">Observe · Correlate · Assess · Decide · Act · Record · Monitor · Reassess</p></div><div className="stats"><Stat label="Reports" value={`${visible.length}/${replay.decisions.length}`} /><Stat label="Incidents" value={incidents.length} /><Stat label="Active" value={active} alert /><Stat label="Resolved" value={resolved} good /><Stat label="Reviews" value={reviews} /><Stat label="Conflicts" value={conflicts} alert /></div></header>
    <section className="controls"><div><span className="pulse" />Replay position <strong>{index + 1} / {replay.decisions.length}</strong></div><nav><button onClick={() => move(index - 1)} disabled={index === 0}>← Previous</button><button className="primary" onClick={() => setPlaying((value) => !value)}>{playing ? 'Pause' : 'Play'}</button><button onClick={() => move(index + 1)} disabled={index === replay.decisions.length - 1}>Next →</button><button onClick={() => move(0)}>Restart</button><label>Speed <select value={speed} onChange={(event) => setSpeed(Number(event.target.value))}><option value={1400}>Slow</option><option value={900}>Normal</option><option value={450}>Fast</option></select></label></nav><input aria-label="Replay position" type="range" min="0" max={replay.decisions.length - 1} value={index} onChange={(event) => move(Number(event.target.value))} /></section>
    <div className="top-grid"><section className="panel"><Title eyebrow="INCOMING REPORT" title={`Evidence received · ${current.prediction.report_id}`}><Badge value={sourceLabel(current)} kind="source" /></Title><div className="report-fields"><Field label="Reported time" value={current.incomingReport.timestamp || 'Not supplied'} /><Field label="Location" value={current.incomingReport.location || 'Not supplied'} /><Field label="Category" value={current.incomingReport.category || 'Not supplied'} /><Field label="Reported severity" value={current.incomingReport.reportedSeverity ?? 'Not supplied'} /><Field label="Reporter type" value={current.incomingReport.reporterType || 'Not supplied'} /></div><p className="description">{current.incomingReport.description || 'No description supplied.'}</p><p className="hint">Reporter-provided evidence. The decision below is the recorded agent assessment.</p><div className="decision"><Decision decision={current} /></div><p className="reason"><b>Decision note:</b> {current.reason}</p></section><section className="panel"><Title eyebrow="CURRENT DECISION" title={current.prediction.incident_id}><Badge value={current.prediction.relationship} kind="relationship" /></Title><Decision decision={current} /><div className={`review ${current.prediction.human_review ? 'needed' : ''}`}>{current.prediction.human_review ? <><b>! Human review requested</b><span>Uncertainty or consequence requires oversight.</span></> : <b>✓ No human review requested</b>}</div></section></div>
    <section className="panel log"><Title eyebrow="DECISION LOG" title={`${filtered.length} recorded decisions`}><div className="filters"><Filter label="All" active={filters.includes('ALL')} onClick={() => toggle('ALL')} /><Filter label="Review" active={filters.includes('REVIEW')} onClick={() => toggle('REVIEW')} />{relationships.map((value) => <Filter key={value} label={value} active={filters.includes(value)} onClick={() => toggle(value)} />)}</div></Title><div className="table-wrap"><table><thead><tr><th>Report</th><th>Incident</th><th>Relationship</th><th>Severity</th><th>Confidence</th><th>Action / service</th><th>Status</th><th>Review</th><th>Decision note</th></tr></thead><tbody>{filtered.map((decision) => <tr key={decision.position} className={current.position === decision.position ? 'chosen' : ''} tabIndex={0} onClick={() => { move(decision.position - 1); }} onKeyDown={(event) => { if (event.key === 'Enter') move(decision.position - 1); }}><td><b>{decision.prediction.report_id}</b><small>#{decision.position}</small></td><td>{decision.prediction.incident_id}</td><td><Badge value={decision.prediction.relationship} kind="relationship" /></td><td><Badge value={decision.prediction.severity} kind="severity" /></td><td><Confidence value={decision.prediction.confidence} /></td><td>{actionsText(decision.prediction.actions)}</td><td><Badge value={decision.prediction.incident_status} kind="status" /></td><td>{decision.prediction.human_review ? <b className="review-text">Review</b> : '—'}</td><td>{decision.reason}</td></tr>)}</tbody></table></div></section>
    <div className="bottom-grid"><section className="panel"><Title eyebrow="INCIDENT EXPLORER" title={`${incidents.length} known incidents`}><span className="hint">Select an incident</span></Title><div className="incident-list">{incidents.map((item) => <button key={item.incident.incidentId} className={detail?.incident.incidentId === item.incident.incidentId ? 'incident selected' : 'incident'} onClick={() => setSelected(item.incident.incidentId)}><span><b>{item.incident.incidentId}</b><small>{item.incident.normalizedType} · {item.incident.canonicalLocation || 'location unavailable'}</small></span><Badge value={item.last.prediction.incident_status} kind="status" /><small>{item.decisions.length} reports · {confidence(item.last.prediction.confidence)}</small>{item.conflicts > 0 && <em>{item.conflicts} conflict{item.conflicts === 1 ? '' : 's'}</em>}</button>)}</div>{detail && <Explorer item={detail} />}</section><section className="panel"><Title eyebrow="ACTION HISTORY" title="Operational response"><span className="hint">Through replay point</span></Title><div className="actions">{incidents.flatMap((item) => item.actions.map((entry) => ({ ...entry, id: item.incident.incidentId }))).sort((a, b) => a.decision.position - b.decision.position).map((entry) => <div className="action" key={`${entry.id}-${entry.decision.position}-${entry.action.type}`}><i className={entry.action.type === 'CLOSE_INCIDENT' ? 'close' : ''}>{entry.action.type === 'CLOSE_INCIDENT' ? '✓' : entry.action.type === 'CONTINUE_RESPONSE' ? '↻' : '→'}</i><div><b>{entry.action.type}</b><p>{entry.action.service_id ?? 'Incident lifecycle'} · {entry.id}</p><small>Report {entry.decision.prediction.report_id} · #{entry.decision.position} · {entry.decision.prediction.incident_status}</small></div></div>)}</div><p className="action-note"><b>New action:</b> dispatch, escalation, verification, closure. <b>↻ Continue:</b> response remains appropriate. <b>No new action:</b> explicitly shown in the decision log.</p></section></div>
  </main>;
}
function Stat({ label, value, alert = false, good = false }: { label: string; value: string | number; alert?: boolean; good?: boolean }) { return <div className={`stat ${alert ? 'alert' : ''} ${good ? 'good' : ''}`}><small>{label}</small><b>{value}</b></div>; }
function Field({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><b>{value}</b></div>; }
function Title({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) { return <div className="title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{children}</div>; }
function Filter({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) { return <button className={active ? 'filter active' : 'filter'} onClick={onClick}>{label}</button>; }
function Decision({ decision }: { decision: DecisionTrace }) { return <div className="decision-fields"><div><small>Relationship</small><Badge value={decision.prediction.relationship} kind="relationship" /></div><div><small>Assessed severity</small><Badge value={decision.prediction.severity} kind="severity" /></div><div><small>Confidence</small><Confidence value={decision.prediction.confidence} /></div><div><small>Incident status</small><Badge value={decision.prediction.incident_status} kind="status" /></div><div><small>Recorded action</small><b>{actionsText(decision.prediction.actions)}</b></div></div>; }
function Explorer({ item }: { item: IncidentAtPoint }) { const status = item.decisions.map((decision) => decision.prediction.incident_status).filter((value, index, all) => index === 0 || value !== all[index - 1]).join(' → '); const severity = item.decisions.map((decision) => decision.prediction.severity).filter((value, index, all) => index === 0 || value !== all[index - 1]).join(' → '); const confidenceHistory = item.decisions.map((decision) => confidence(decision.prediction.confidence)).join(' → '); return <div className="detail"><div className="detail-fields"><Field label="Current severity" value={item.last.prediction.severity} /><Field label="Confidence" value={confidence(item.last.prediction.confidence)} /><Field label="Services" value={item.incident.services.join(', ') || 'None'} /><Field label="Review flags" value={String(item.reviews)} /></div><h3>Lifecycle</h3><p>{status}</p><h3>Severity evolution</h3><p>{severity}</p><h3>Confidence evolution</h3><p>{confidenceHistory}</p><h3>Incident actions</h3><p>{item.actions.map((entry) => actionLabel(entry.action)).join(' → ') || 'No operational action recorded.'}</p><h3>Linked evidence</h3><ol>{item.decisions.map((decision) => <li key={decision.position}><b>{decision.prediction.report_id}</b> · {decision.incomingReport.description || 'No description supplied.'}{decision.prediction.relationship === 'CONFLICT' && <Badge value="CONFLICT" kind="relationship" />}</li>)}</ol></div>; }
