import { describe, expect, it } from 'vitest';
import type { DecisionTrace, Replay } from '../models';
import { currentIncidentId, decisionsThrough, filterDecisions, incidentsAtPoint, isReplay, sourceLabel } from './replay-view';

const decision = (position: number, relationship: DecisionTrace['prediction']['relationship'], review = false): DecisionTrace => ({ position, incomingReport: { reportId: `R${position}`, timestamp: '', location: 'Library', locationKey: 'library', category: 'it', type: 'it', reportedSeverity: 'MEDIUM', description: `Evidence ${position}`, descriptionKey: `evidence ${position}`, tokens: [], reporterType: 'staff' }, prediction: { report_id: `R${position}`, incident_id: 'I001', relationship, severity: position === 2 ? 'HIGH' : 'MEDIUM', confidence: 0.6 + position / 10, actions: position === 1 ? [{ type: 'DISPATCH', service_id: 'SVC-IT' }] : [], incident_status: position === 2 ? 'ACTIVE' : 'INVESTIGATING', human_review: review }, reason: 'Recorded decision.', correlation: { score: .8, signals: [], candidates: [] }, groq: { used: false, fallback: false } });
const replay: Replay = { generatedAt: '', decisions: [decision(1, 'NEW'), decision(2, 'CONFLICT', true), { ...decision(3, 'RESOLUTION'), prediction: { ...decision(3, 'RESOLUTION').prediction, incident_id: 'I003' } }], incidents: [{ incidentId: 'I001', normalizedType: 'it', canonicalLocation: 'library', severity: 'MEDIUM', confidence: .9, status: 'RESOLVED', linkedReportIds: ['R1', 'R2'], evidence: [], services: ['SVC-IT'], actionHistory: [], severityHistory: [], confidenceHistory: [], statusHistory: [], conflictCount: 1, reviewCount: 1 }, { incidentId: 'I003', normalizedType: 'it', canonicalLocation: 'residence', severity: 'MEDIUM', confidence: .9, status: 'RESOLVED', linkedReportIds: ['R3'], evidence: [], services: ['SVC-IT'], actionHistory: [], severityHistory: [], confidenceHistory: [], statusHistory: [], conflictCount: 0, reviewCount: 0 }], statistics: {} };

describe('dashboard replay views', () => {
  it('uses the replay decision count and clamps replay navigation', () => { expect(decisionsThrough(replay, 1)).toHaveLength(2); expect(decisionsThrough(replay, 99)).toHaveLength(3); expect(decisionsThrough(replay, -1)).toHaveLength(0); });
  it('shows all three processed decisions at replay position three by default and selects its incident', () => { const throughThree = decisionsThrough(replay, 2); expect(filterDecisions(throughThree, ['ALL'])).toHaveLength(3); expect(filterDecisions(throughThree, ['CONFLICT'])).toHaveLength(1); expect(currentIncidentId(replay, 2)).toBe('I003'); });
  it('derives selected incident evidence, conflicts, reviews, and actions from recorded decisions', () => { const incident = incidentsAtPoint(replay, 1)[0]; expect(incident?.decisions).toHaveLength(2); expect(incident?.conflicts).toBe(1); expect(incident?.reviews).toBe(1); expect(incident?.actions[0]?.action.service_id).toBe('SVC-IT'); });
  it('keeps source labels safe and rejects malformed replay data', () => { expect(sourceLabel(replay.decisions[0]!)).toBe('Deterministic'); expect(isReplay(replay)).toBe(true); expect(isReplay({ decisions: [] })).toBe(false); });
});
